require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.0

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 122

Metrics/MethodLength:
  Max: 16

Naming/FileName:
  Exclude:
     - 'lib/icalendar-rrule.rb'
     - 'lib/icalendar/schedulable-component.rb'
     - 'lib/icalendar/scannable-calendar.rb'
     - 'spec/icalendar/scannable-calendar_spec.rb'
     - 'spec/icalendar/schedulable-component_spec.rb'



Metrics/ModuleLength:
   Enabled: false

Style/DocumentationMethod:
  Description: 'Public methods.'
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'




# inherit_from: .rubocop_todo.yml